from fastapi import FastAPI, WebSocket, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import redis
import json
import os
import asyncio
from typing import List, Optional
from datetime import datetime
import asyncpg

app = FastAPI(title="Road Traffic Gateway API - Production Ready")

# Security: CORS configuration
origins = [
    "http://localhost:3000",  # Next.js Frontend
    "http://127.0.0.1:3000",
    "*"  # Dev fallback
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Setup Redis connection
REDIS_HOST = os.getenv("REDIS_HOST", "localhost")
REDIS_PORT = int(os.getenv("REDIS_PORT", 6379))
r = redis.Redis(host=REDIS_HOST, port=REDIS_PORT, db=0, decode_responses=True)

# Setup PostgreSQL configuration
POSTGRES_HOST = os.getenv("POSTGRES_HOST", "localhost")
POSTGRES_PORT = int(os.getenv("POSTGRES_PORT", 5432))
POSTGRES_DB = os.getenv("POSTGRES_DB", "traffic_db")
POSTGRES_USER = os.getenv("POSTGRES_USER", "user")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD", "password")

db_pool = None

@app.on_event("startup")
async def startup_event():
    global db_pool
    # Connect to PostgreSQL pool
    retries = 5
    while retries > 0:
        try:
            db_pool = await asyncpg.create_pool(
                host=POSTGRES_HOST,
                port=POSTGRES_PORT,
                database=POSTGRES_DB,
                user=POSTGRES_USER,
                password=POSTGRES_PASSWORD,
                min_size=1,
                max_size=10
            )
            print("✅ Connected to PostgreSQL pool")
            break
        except Exception as e:
            print(f"⚠️ Failed to connect to PostgreSQL: {e}. Retrying in 3s...")
            retries -= 1
            await asyncio.sleep(3)
            
    if not db_pool:
        print("❌ Critical: Could not connect to PostgreSQL. App will run in degraded mode (No history).")

@app.on_event("shutdown")
async def shutdown_event():
    global db_pool
    if db_pool:
        await db_pool.close()
        print("🔌 PostgreSQL pool closed")

class TrafficData(BaseModel):
    DateTime: str
    Junction: int
    Vehicles: Optional[int] = None
    ID: Optional[int] = None

@app.get("/")
def read_root():
    return {
        "status": "online", 
        "service": "traffic-gateway-api",
        "database_connected": db_pool is not None
    }

@app.post("/traffic/ingest")
async def ingest_traffic(data: TrafficData):
    """
    HTTP Ingest fallback endpoint. Pushes data directly into Redis Pub/Sub traffic_stream.
    (Note: Simulator now publishes directly to Kafka, which Spark processes).
    """
    try:
        payload = data.dict()
        r.publish("traffic_stream", json.dumps(payload))
        r.set(f"junction:{data.Junction}:last", json.dumps(payload))
        return {"status": "success", "message": "Data ingested"}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/traffic/current")
def get_current_traffic():
    """
    Fetch the latest predictions generated by Spark Streaming from Redis.
    """
    keys = r.keys("junction:*:status")
    if not keys:
        # Fallback to last ingested raw data if Spark has not started yet
        keys = r.keys("junction:*:last")
        
    traffic_data = []
    for key in keys:
        val = r.get(key)
        if val:
            traffic_data.append(json.loads(val))
            
    # Sort by junction number
    traffic_data.sort(key=lambda x: x.get("Junction", 0))
    return traffic_data

@app.get("/traffic/history/{junction_id}")
async def get_traffic_history(junction_id: int, limit: int = 50):
    """
    Fetch the historical prediction logs (generated by Spark Streaming) from PostgreSQL.
    """
    if not db_pool:
        # High fidelity mock fallback if database is disconnected
        print("⚠️ Database disconnected. Returning mock history.")
        now = datetime.now()
        mock_history = []
        for i in range(limit):
            dt = datetime.fromtimestamp(now.timestamp() - i * 3600)
            mock_history.append({
                "timestamp": dt.strftime("%Y-%m-%d %H:%M:%S"),
                "junction_id": junction_id,
                "actual_vehicles": int(20 + (i % 7) * 5 + (i % 3) * 2),
                "predicted_vehicles": float(18 + (i % 7) * 5 + (i % 3) * 2.2)
            })
        return mock_history

    try:
        records = await db_pool.fetch(
            """
            SELECT timestamp, junction_id, actual_vehicles, predicted_vehicles
            FROM predictions
            WHERE junction_id = $1
            ORDER BY timestamp DESC
            LIMIT $2
            """,
            junction_id,
            limit
        )
        
        history = []
        for rec in records:
            history.append({
                "timestamp": rec["timestamp"].strftime("%Y-%m-%d %H:%M:%S"),
                "junction_id": rec["junction_id"],
                "actual_vehicles": rec["actual_vehicles"],
                "predicted_vehicles": rec["predicted_vehicles"]
            })
            
        history.reverse()
        return history
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Database error: {str(e)}")

@app.websocket("/ws/traffic")
async def websocket_endpoint(websocket: WebSocket):
    await websocket.accept()
    pubsub = r.pubsub()
    # Subscribe to raw input streams and Spark prediction updates
    pubsub.subscribe("traffic_updates")
    pubsub.subscribe("traffic_stream")
    
    print("🔌 Client connected to WebSocket /ws/traffic")
    try:
        while True:
            # Responsive non-blocking message loop
            message = pubsub.get_message(ignore_subscribe_message=True)
            if message:
                await websocket.send_text(message['data'])
            await asyncio.sleep(0.05)
    except Exception as e:
        print(f"🔌 WebSocket Disconnected: {e}")
    finally:
        try:
            pubsub.unsubscribe()
        except:
            pass
        await websocket.close()
